### ISSUE TITLE
Filter term does not filter, it only sorts. 

### ISSUE THREAD

**Issue by Zzmobie** [CS2103AUG2017-F11-B1/main#72]
The sorting that the dropdown does should be labelled appropriately. Since it does not filter, but instead sorts the addressbook, shouldn't you label it "sort by" instead of "filter by"?

It's also extremely unusual to sort by phone number/address/email. Why would a user want to do that? What is your user profile?

**Comment by sofarsophie** [comment]
Our user profile, as stated in the user guide, are insurance sellers with a long list of clientele and colleagues. 

I think the term `filter` is interpreted differently by different people. We named it 'filter by' because 'sort' is a not a very user-friendly term - it feels quite technical. Will change the wording to be extra clear. Thanks for the suggestion! :)

**Comment by sofarsophie** [comment]
Updated in PR #87
