### ISSUE TITLE
Poorly documented commands in user guide - list command

### ISSUE THREAD

**Issue by Zzmobie** [CS2103AUG2017-F11-B1/main#82]
The list command supports multiple entries that is searched across the tag and group fields, but the user guide description specifies that only 1 tag and 1 group can be keyed in, and specifically in the order [TAG] [GROUP] which isn't true.

**Comment by Zzmobie** [comment]
Is there any real distinction between list and find? the only real difference is that list searches through tags and groups while find searches through the other fields. Why don't you combine these two functions appropriately?

**Comment by kengying** [comment]
There's no specific order for it, it's just an example for the command. Finding is more for finding that one particular person, while listing is to show the group/tag

**Comment by sofarsophie** [comment]
To add on, please note that our target users are Insurance Sellers! They typically have a huge list of clients and colleagues. So a `list` command would be used to list people who are in a specific group / tag (ex. people who are retired) while a `find` command is for finding one exact person (ex. an unknown number in phone -> find that number). Hope that clarifies! :)

**Comment by Zzmobie** [comment]
If there isn't a specific order, shouldn't you specify it in the format? As of now, in the user guide/function description, it looks like the format is precisely "list [TAG] [GROUP]". Why not write it as [TAG]...? Or even list [SEARCH_TERM]... , and additionally describe each SEARCH_TERM as searched under both the tags and groups of a person since there is no real distinction?

That's not really the point I'm making. I'm trying to say that the two commands are functionally the same, so why are they named differently? Why not have them both be called find or both be called list? It isn't intuitive to the user why I have to use list when I'm searching for a group/tag, but I have to use find when I'm searching for phone/address. The reason you gave seems kinda artificial...? If you really wanted the find command to be specifically for one person, shouldn't it not search for partial phone number matches? Shouldn't it match names precisely instead of including substring matches too? Shouldn't it return an error if there is more than 1 match?

**Comment by syy94** [comment]
> If there isn't a specific order, shouldn't you specify it in the format? As of now, in the user guide/function description, it looks like the format is precisely "list [TAG] [GROUP]". Why not write it as [TAG]...? Or even list [SEARCH_TERM]... , and additionally describe each SEARCH_TERM as searched under both the tags and groups of a person since there is no real distinction?

Yes I agree that it may be better to change `[TAG]` and `[GROUP]` to `[TAG]...` and `[GROUP]...` as this was the exactly how the function works. However, I will have to disagree on changing it to `[SEARCH_TERM]...` as users will then misunderstand, thinking that `[SEARCH_TERM]...` suggest that they can they can use this function to list people by their names or phone numbers.

> That's not really the point I'm making. I'm trying to say that the two commands are functionally the same, so why are they named differently?

>  It isn't intuitive to the user why I have to use list when I'm searching for a group/tag, but I have to use find when I'm searching for phone/address.

> Why not have them both be called find or both be called list? 

But as you said, this was not your point. I also recognize that both list and find functions are extremely similar but consider this. `Persons`  are part of `Groups` and `Tags`  while `Name`, `Phone`, etc makes up `Persons`. 

Yes both can be named `find` but since `Name`, `Phone` have different logical relationships with `Person` as compared to `Groups` and `Tags` therefore, we designed this commands to be separated as even though the methods are the same, the result holds different meanings.

It is also not intuitive to use `list` when your are trying to find something as you do not list your questions on Google, you `find` or `search` your problem on Google.

> If you really wanted the find command to be specifically for one person, shouldn't it not search for partial phone number matches? Shouldn't it match names precisely instead of including substring matches too? Shouldn't it return an error if there is more than 1 match?

Additionally, we allow partial matches is due to the fact that we want to help the user narrow down the result to the person he wanted. Imagine going to google and searching `Java` and then receiving the only result being the definition of `Java`. What would google be as an search engine if that happens?

> The reason you gave seems kinda artificial...? 

As `Persons`  are part of `Groups` and `Tags`, will it be more intuitive by using `list`, as it would suggest that the user is trying to list all possible `Persons` in the requested `Groups` or `Tags`. 

Another resaon is that if we were to make `Groups` and `Tags` searchable in the `find` command and if there are 1000 `persons` in the group `Health` and with 50 `persons` sharing the name `Alphonse` , `find` will then be not really helpful in this scenario due to the fact that, `find g/Health n/Alphonse` find will return all `persons` who are in the group `Health` and all everyone sharing the name `Alphonse`. Then one will argue what is the point of the `find` command when it returns so many values.

**Comment by Zzmobie** [comment]
I mean you could just specify what SEARCH_TERM  has to be, or even a more descriptive tag like TAG_OR_GROUP. Oops for a second I thought the ordering mattered, but since it doesn’t I guess it’s fine. 

“But as you said, this was not your point” errr ???

Well I only bring it up because I was super confused when I was using it, however you want to implement it is completely up to you lol. 

The point I was making when I said all the stuff about more than 1 result being shown for find, is that what your command does is inconsistent with what you said before, that list is supposed to show a bunch of people, and find is supposed to help you find one. I was trying to make the point that they are the same thing, that the reason you gave doesn’t make sense, not that you should remove that functionality. 

Your last example doesn’t seem to make much sense? So what if find supports groups and tags, how does it remove any functionality? It’s not like your current implementation can do a search with both name and group right? You can still do the individual queries with the appropriate tags, so the ability to specify both group and name is a strict upgrade in functionality. You could even add a different mode if you want to enforce certain search criteria to be satisfied. 

Again, I’m not saying that find should return only 1 value. It’s precisely because it shouldn’t/doesn’t that the two functionalities are basically identical and at least I would merge them. 

Not sure why I even bother replying to these lol, how you want to implement your addressbook is not my problem at all.

**Comment by syy94** [comment]
I am sorry that you feel that way but I was just trying my best to explain our rational behind the design of this 2 commands and as you can see, my grasp of the English language is not that strong.

The point that I was trying to get across is that we are trying to structure our display such that a groups and tags can be listed and details of a person can found (find).

To try to understand your thinking better, I went to your personal repository to find inspiration on how to properly unify this 2 commands. However I seemed to observe that you have this command:

`list m/tag t/tag`

Based on your argument, this command should be changed to `find m/tag t/tag` as it is not intuitive to the user as to why he have to use `list` when he is searching for a tag. 

> It’s precisely because it shouldn’t/doesn’t that the two functionalities are basically identical and at least I would merge them.

With this argument, one could also argue that your 'find NAME` command can also be expressed as `list NAME` as the user may be allowed to list persons that matches the `NAME` entered and your 'list m/tag t/tag` command can also be expressed as `find m/tag t/tag` which as you described to be more intuitive for the user to find a `tag` as compared to listing tags. Does this suggest that your `list` and `find` commands are both of the same functionality and therefore, should be merged?

In addition, your `find` and `findregex` commands are also basically identical with only a change in input. Will you be merging them in the near future? Maybe the user should enter `find r/NAME_WITH_REGEX` if they want to use the find function with regex and `find NAME` if they want to use the default `find`?

I humbly apologize for bringing up your commands to better understand your arguments but I am also rather confused by what you are suggesting us to do and comparing with what you actually did. I also understand that your implementation is totally up to you.

I thank you for your time in discussing this problem with us and I hope my inefficiencies in the English language will not hamper this productive discussion on improving our application. We value your inputs immensely and hope to clarify your confusion regarding our `find` and `list` command.

**Comment by Zzmobie** [comment]
Did you actually look through my personal repository trying to obtain a better understanding of the implementation, or did you simply search through, looking for the first error to come at me with? It sure does feel like the latter. 

Did you even try and download the .jar file in the v1.4 release? Did you perhaps notice that the "list" command mysteriously does not have a (Since v1.x) tag? If you had actually tried our application, and had actually tried the list function, you would have noticed that it only lists all the addressbook entries. None of those things described in the user guide exist. It's just an error on our part not to have changed our original proposal for the list command. (Thanks for the minor text bug found!)

And hey, look! We originally had our list command list tag searches too, but now, but you can quite clearly see that it is implemented as a findtag command instead. I wonder why? Perhaps it's because as a team, we discussed this, and decided to place all find commands together...? Perhaps it's because we actually gave this topic some thought, instead of just working as individuals, pushing our own implementations, then merging them...?

We actually did put everything with the same functionality under the same name, "find____", so that users would not be confused. 

"In addition, your find and findregex commands are also basically identical with only a change in input. Will you be merging them in the near future? Maybe the user should enter find r/NAME_WITH_REGEX if they want to use the find function with regex and find NAME if they want to use the default find?"

Man this is like the lamest nitpick ever. Sure, we could have included a mode for regex searches, or let it be on a separate marker, but is there a clear advantage with this implementation, over simply having it in the name? It's not as if findregex is a confusing, un-intuitive name, which is the main problem with having "search"-esque commands with both find and list prefixes. 

You know, I think I realised something. Perhaps if a stronger team had implemented the search/find functions separately, and provided the above explanation for separating them, it would have been totally cool. I think I would have accepted that it was a conscious design choice. It's just extremely difficult to find that to be the case, when your entire project reeks of poorly merged implementations, and shoddily done work. When I first saw the two distinct commands, you know what it looks like? It looks precisely like two people had individually decided to implement search functions, and without discussing it with each other, they implemented it on their owns, and with separate command keyphrases. That's how it comes off to an outside developer. 

Whatever you want to take away from this is totally up to you. I'm just giving you feedback, however you want to take it, however you want to justify the changes is entirely up to you. Have fun defending yourselves against similar criticisms if they appear during the actual demo.

**Comment by kengying** [comment]
Hi, i think your last second paragraph is too much. We as a team talk it through and decided what to implement. We did all the discussion and it is very hurtful for you to just say we look like we did not discuss it. I'm sorry that our team is not that strong and came out with such a weak implementation. I know that i'm not good at codding, and i'm trying to improve myself. Thanks for all the suggestions

**Comment by syy94** [comment]
Thank you for you opinions.

Firstly I would  like say that everything I typed was the act of myself and not the voice as a group.

**Comment by syy94** [comment]
I'll admit that I was under the impression that the local repository should reflect the forked repository and I'll also admit that I did not download and test your obliviously stronger group's work.

> ... had implemented the search/find functions separately, and provided the above explanation for separating them, it would have been totally cool

You said this yourself, but before I came in and "explained", my 2 team members have already explained this to you, and yet you still insisted that the 2 commands should be merged.  

> Sure, we could have included a mode for regex searches, or let it be on a separate marker, but is there a clear advantage with this implementation, over simply having it in the name?

So how is it fair that you can say that there is a clear advantage with the ways that your group does their commands and everyone else must change to be similar to yours?

> Did you actually look through my personal repository trying to obtain a better understanding of the implementation, or did you simply search through, looking for the first error to come at me with?

And finally I replied because i wonder if you questioned us because you are really confused, or are you trying to prove that your method of implementation is better and at the same time earn higher grades because you helped another group? It sure does feel like the latter. 

Whatever you want to take away from this is totally up to you. I'm just giving you feedback, however you want to take it, however you want to justify your actions, it is totally up to you.

And since this is getting toxic, I'll be closing this Issue. If you still want to argue your point, feel free to create a new issue on my personal repository. I'll be happy to hear and clarify any opinions you have, including insults, but please direct them at me and not my group mates because I seem to be the one annoying you. Thank you.

**Comment by Zzmobie** [comment]
Lul it's actually quite funny if you think that everyone cares about their grades like you. I don't think I've ever seen anyone try and put down other people's work for "better grades" rofl. 

I haven't insisted on anyone changing their implementation or anything. If you read the first few comments, since you decided for whatever reason you had to justify the way you implemented these two features, I responded pointing out how illogical your justifications are. I honestly don't care why you want to implement it this way. 

What irritates me is this need to justify your decisions post evaluation with poor arguments "obviously" constructed in the moment for ??? reasons, and this consistent lack of structure in your arguments, when all of your premises are poorly researched/established. It's this weirdly commonplace behavior of talking out of your ass to defend yourself when confronted with anything. 

It feels like you didn't put much though into this thing, but for some reason decided to pretend that you did. It's incredibly annoying that this is acceptable, commonplace behavior. 

It's almost as if you want me to reply.

**Comment by syy94** [comment]
Thank you for your humble opinions I will take it to heart and I'll be happy to hear and clarify any opinions you have, including insults. Feel free to create a new issue on my **personal repository**. Thank you.
